default_forum_layout
discord-php/DiscordPHP pull request #1009
Opened 2022-12-07 15:54 UTC by key2peace

https://github.com/discord/discord-api-docs/pull/5693

2022-12-07 16:12 UTC, SQKo requested changes
Also might want to add the `FORUM_LAYOUT_TYPE_x` constants from:
https://github.com/discord/discord-api-docs/pull/5693/files#diff-160acb4654c611c67c4ee46b2ce5dda2be82212af8d1d00cd0256ef6edda1e95R92

2022-12-07 16:13 UTC, SQKo commented on src/Discord/Parts/Channel/Channel.php
> + * @property      ?int|null           $default_forum_layout               The default layout type used to display posts in a forum channel.
docs show `default_forum_layout? | integer` means optional but not nullable (it's reverse side in our code)
`field?` = optional field = `field?`
`?int` = nullable integer = `?integer`

2022-12-10 11:19 UTC, key2peace commented
> Also might want to add the `FORUM_LAYOUT_TYPE_x` constants from: https://github.com/discord/discord-api-docs/pull/5693/files#diff-160acb4654c611c67c4ee46b2ce5dda2be82212af8d1d00cd0256ef6edda1e95R92

I did fix the SORT_ORDER_CREATION_DATE, I don't think we need a copy of SORT_ORDER_* as FORUM_LAYOUT_TYPE_*, as both sort orders would be identical

2022-12-10 11:27 UTC, SQKo approved these changes

2022-12-10 11:27 UTC, merged