Add CREATE_EVENTS permission
discord-php/DiscordPHP pull request #1154
Opened 2023-07-15 14:24 UTC by jocafamaka

New permission `CREATE EVENTS` not yet documented but already out.

Discussion: https://github.com/discord/discord-api-docs/issues/6298

2023-07-16 05:24 UTC, SQKo commented
The `create_events` value is wrong, it is 44 not 43.
Also please put in the correct order of the bits

2023-07-22 13:14 UTC, SQKo requested changes

2023-07-22 13:14 UTC, SQKo commented on src/Discord/Parts/Permissions/ChannelPermission.php
> + * @property bool $create_events            Allows for creating scheduled events
please also move this between use_soundboard and use_external_sounds

2023-07-22 13:14 UTC, SQKo commented on src/Discord/Parts/Permissions/RolePermission.php
> + * @property bool $create_events
please also move this between use_soundboard and use_external_sounds

2023-10-08 18:06 UTC, key2peace commented
[this link](https://github.com/discord/discord-api-docs/issues/6298#issuecomment-1637297533) also talks about the requirement to add the ``x-super-properties header`` header to your requests in order to support it, which is not present [here](https://github.com/discord-php/DiscordPHP-Http/blob/master/src/Discord/Http.php#L266-L276)

2023-10-13 15:56 UTC, SQKo commented
> [this link](https://github.com/discord/discord-api-docs/issues/6298#issuecomment-1637297533) also talks about the requirement to add the `x-super-properties` header to your requests in order to support it, which is not present [here](https://github.com/discord-php/DiscordPHP-Http/blob/master/src/Discord/Http.php#L266-L276)

That is not something the bot usually use, the header is sent by discord clients

2024-01-09 00:22 UTC, jocafamaka commented
It appers the permissions requirements will not affect bots, but it still aply to roles and users.

https://github.com/discord/discord-api-docs/commit/8d9f1fb17458f7372c1a2c6b029e397483c8be2f

2024-03-02 03:11 UTC, SQKo approved these changes
need to test

2024-03-03 09:31 UTC, merged