Send Private Message using Member Object
discord-php/DiscordPHP pull request #538
Opened 2021-05-22 13:08 UTC by MohsinEngineer

Feature request #537

2021-05-22 22:25 UTC, davidcole1340 requested changes
Thanks for the PR, just one small change?

2021-05-22 22:25 UTC, davidcole1340 commented on src/Discord/Parts/User/Member.php
> +        });
```suggestion
        return $this->user->sendMessage($message, $tts, $embed);
```
Just for better code reuse.

2021-05-24 08:46 UTC, MohsinEngineer commented on src/Discord/Parts/User/Member.php
> +        });
LGTM!

2021-06-02 01:43 UTC, davidcole1340 approved these changes

2021-06-02 01:43 UTC, merged