Avoid hexdec deprecated warning (PHP 7.4+)
discord-php/DiscordPHP pull request #606
Opened 2021-10-03 14:50 UTC by jocafamaka

Avoid deprecated warning, and possible future error:
```
Deprecated: Invalid characters passed for attempted conversion, these have been ignored in ***/vendor/team-reflex/discord-php/src/Discord/Parts/Embed/Embed.php on line 484
```

Sanitization performed before parse to conversion.

2021-10-03 15:25 UTC, SQKo commented
I don't see why it is necessary, in PHP passing hex color should be just this way:
```php
'color' => '2c2c2c'
```
or
```php
'color' => 0x2c2c2c;
```
or
```php
'color' => 0x2c2c2c;
```
And those are valid with hexdec in php 7.4

Also Discord API treat the colors with int values, I think that doing '#2c2c2c' is user specific behavior, not caused or limited by API or even the language itself, so conversion should be done manually by the user.

2021-10-03 15:46 UTC, jocafamaka commented
I get that, but if it's something that might break the lib in the future, why not treat it? It's a harmless change.

The vast majority of users (myself included) use decimal colors this way, largely because it's standard in CSS.

And even other parts of the code imply that this is valid:
https://github.com/discord-php/DiscordPHP/blob/c635bcb5bd554284f7e77f088b23081ea62a1edd/src/Discord/functions.php#L95-L113

And the deprecated message can be quite annoying, in addition to becoming a fatal error in future versions of PHP.

2021-10-03 16:22 UTC, SQKo commented
This library is made for php 7.4+ so avoiding the errors suggested is a bad move

the getColor function provided in functions.php is a helper/support function for user to use, it is not used anywhere in the library.

If the goal is only to allow CSS format color code, then a simple check and remove for the first '#' is enough than using regex to replace all invalid characters which is overkill

Even worse, if the converted color code is invalid, Discord API will silently not show the Embed.

2021-10-03 17:52 UTC, jocafamaka commented
> If the goal is only to allow CSS format color code, then a simple check and remove for the first '#' is enough than using regex to replace all invalid characters which is overkill

So be it, my goal is just to make things easier!

> Even worse, if the converted color code is invalid, Discord API will silently not show the Embed.

You say this as if this change would allow this behavior, which is already what happens, clearly if the hex code is wrong it won't work.

2021-10-03 19:59 UTC, SQKo commented on src/Discord/Parts/Embed/Embed.php
> +            return hexdec((preg_replace('/[^0-9a-fA-FxX]/', '', (string) $color)));
replace with
```php
return hexdec((str_replace('#', '', (string) $color)));
```

2021-10-03 20:00 UTC, SQKo requested changes
This should be enough i guess?

2021-10-03 20:12 UTC, jocafamaka commented
>This should be enough i guess?

I believe so!

2021-10-04 00:27 UTC, davidcole1340 approved these changes
Thanks!

2021-10-04 00:27 UTC, merged