Implement Guild Stage Instance
discord-php/DiscordPHP pull request #643
Opened 2021-12-13 14:12 UTC by SQKo

- Add Stage Instance Repository
- Add Stage Instance Part
- Add Stage Instance into Guild
- Add Stage Instances event handlers

DOES NOT WORK FOR BOTS!! (yet, maybe in future they might add it, just re-open this)
```
[2021-12-13T14:01:07.366843+00:00] DiscordPHP.WARNING: REQ GET stage-instances failed: Discord\Http\Exceptions\NoPermissionsException: Forbidden - {     "message": "Bots cannot use this endpoint",
   "code": 20001 }
```

2021-12-14 07:27 UTC, SQKo commented
Reopening this because I got it working now

2021-12-14 07:51 UTC, davidcole1340 commented on src/Discord/Parts/Channel/StageInstance.php
> + * @property Guild   $guild                 The guild that the stage instance associated to.
`Guild|null`? Not sure if the guild is nullable here but on `getGuildAttribute()` it has `?Guild`

2021-12-14 07:54 UTC, davidcole1340 requested changes

2021-12-14 07:54 UTC, davidcole1340 commented on src/Discord/Parts/Channel/StageInstance.php
> +        var_dump($this->channel_id);
```suggestion
```

2021-12-14 07:54 UTC, davidcole1340 commented on src/Discord/WebSockets/Events/StageInstanceCreate.php
> +            $this->discord->guilds->push($guild);
```suggestion
```
Don't need this line, was a mistake I made throughout the library earlier. PHP objects are reference counted, so `->get()` will return the object reference AFAIK

2021-12-14 07:54 UTC, davidcole1340 commented on src/Discord/WebSockets/Events/StageInstanceDelete.php
> +            $this->discord->guilds->push($guild);
```suggestion
```

As above

2021-12-14 07:54 UTC, davidcole1340 commented on src/Discord/WebSockets/Events/StageInstanceUpdate.php
> +            $this->discord->guilds->push($guild);
```suggestion
```
As above

2022-01-02 20:52 UTC, valzargaming approved these changes

2022-01-02 21:41 UTC, merged