Fix a deprecated error in VoiceClient
discord-php/DiscordPHP pull request #799
Opened 2022-05-16 03:48 UTC by Nerahikada

2022-05-16 08:05 UTC, SQKo requested changes

2022-05-16 08:05 UTC, SQKo commented on src/Discord/Voice/VoiceClient.php
> +        $which = strtoupper(substr(PHP_OS, 0, 3)) === 'WIN' ? 'where' : 'command -v';
```suggestion
        $which = strtoupper(substr(PHP_OS, 0, 3)) === 'WIN' ? 'command -v' : 'where';
```

2022-05-21 17:07 UTC, SQKo commented on src/Discord/Voice/VoiceClient.php
> +        $which = strtoupper(substr(PHP_OS, 0, 3)) === 'WIN' ? 'where' : 'command -v';
My bad, I thought it was causing #790

2022-05-22 20:33 UTC, key2peace approved these changes

2022-05-23 04:53 UTC, SQKo approved these changes

2022-05-23 04:53 UTC, merged