encode opus with ffmpeg
discord-php/DiscordPHP pull request #962
Opened 2022-11-02 12:53 UTC by davidcole1340

woohoo no more dca required, we can just encode opus with ffmpeg. why didn't we do this in the beginning???? also fixed the choppy audio bug in the process

2022-11-03 02:18 UTC, SQKo commented on src/Discord/Exceptions/BufferTimedOutException.php
> +class BufferTimedOutException extends Exception
should extends RuntimException

2022-11-03 02:20 UTC, SQKo commented on src/Discord/Voice/OggPage.php
> + * @see https://www.rfc-editor.org/rfc/rfc3533
```suggestion
 * @link https://www.rfc-editor.org/rfc/rfc3533
```

2022-11-03 02:23 UTC, SQKo commented on src/Discord/Voice/OggPage.php
> +     * @see https://www.rfc-editor.org/rfc/rfc3533 -- Section 6. The Ogg page format
```suggestion
     * @link https://www.rfc-editor.org/rfc/rfc3533 Section 6. The Ogg page format
```

2022-11-03 02:45 UTC, SQKo requested changes
use of @link instead of @see

2022-11-03 02:45 UTC, SQKo commented on src/Discord/Voice/OggPage.php
> + * @see https://www.rfc-editor.org/rfc/rfc3533
```suggestion
 * @link https://www.rfc-editor.org/rfc/rfc3533
```

2022-11-03 02:45 UTC, SQKo commented on src/Discord/Voice/OggPage.php
> +     * @see https://www.rfc-editor.org/rfc/rfc3533 -- Section 6. The Ogg page format
```suggestion
     * @link https://www.rfc-editor.org/rfc/rfc3533#section-6 The Ogg page format
```

2022-11-03 02:45 UTC, SQKo commented on src/Discord/Voice/OggStream.php
> + * @see https://www.rfc-editor.org/rfc/rfc7845.html
```suggestion
 * @link https://www.rfc-editor.org/rfc/rfc7845
```

2022-11-03 02:45 UTC, SQKo commented on src/Discord/Voice/OpusHead.php
> + * @see https://www.rfc-editor.org/rfc/rfc7845.html -- Section 5.1. Identification Header
```suggestion
 * @link https://www.rfc-editor.org/rfc/rfc7845#section-5.1 Identification Header
```

2022-11-03 02:45 UTC, SQKo commented on src/Discord/Voice/OpusTags.php
> + * @see https://www.rfc-editor.org/rfc/rfc7845.html -- Section 5.2. Comment Header
```suggestion
 * @link https://www.rfc-editor.org/rfc/rfc7845#section-5.2 Comment Header
```

2022-11-03 03:20 UTC, SQKo requested changes
code editor friendly formatting

2022-11-03 03:20 UTC, SQKo commented on src/Discord/Voice/OggPage.php
> +     * @return Generator<int, (string|bool)[], mixed, void>
```suggestion
     * @return Generator<int,(string|bool)[],mixed,void>
```

2022-11-03 03:20 UTC, SQKo commented on src/Discord/Voice/OggPage.php
> +                $header = unpack(Self::FORMAT, $data);
```suggestion
                $header = unpack(self::FORMAT, $data);
```

2022-11-03 03:20 UTC, SQKo commented on src/Discord/Voice/OpusHead.php
> +        $head = unpack(Self::FORMAT, $data, 8);
```suggestion
        $head = unpack(self::FORMAT, $data, 8);
```

2022-11-03 03:20 UTC, SQKo commented on src/Discord/Voice/OpusHead.php
> +            $stream_counts = unpack(Self::STREAM_COUNT_FORMAT, $data, 19);
```suggestion
            $stream_counts = unpack(self::STREAM_COUNT_FORMAT, $data, 19);
```

2022-11-05 12:03 UTC, key2peace submitted a review, later dismissed

2022-11-06 09:43 UTC, SQKo approved these changes

2022-11-06 09:44 UTC, merged